// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHotContent(arg1) {
  return window['go']['main']['App']['GetHotContent'](arg1);
}

export function GetMusic(arg1, arg2) {
  return window['go']['main']['App']['GetMusic'](arg1, arg2);
}

export function GetSearch(arg1, arg2) {
  return window['go']['main']['App']['GetSearch'](arg1, arg2);
}
