// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBiliAudio(arg1) {
  return window['go']['main']['App']['GetBiliAudio'](arg1);
}

export function GetBiliMusicRanking() {
  return window['go']['main']['App']['GetBiliMusicRanking']();
}

export function GetBiliSearch(arg1, arg2) {
  return window['go']['main']['App']['GetBiliSearch'](arg1, arg2);
}
