// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetHotContent(arg1:models.Platform):Promise<models.VO>;

export function GetMusic(arg1:models.Platform,arg2:string):Promise<models.VO>;

export function GetSearch(arg1:models.Platform,arg2:string):Promise<models.VO>;
